// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "265af090-adbf-4c08-ac04-b6808ab4cda3");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1538054659);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1538054779);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1538054299);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1538054539);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1538070491);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1538054419);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1538054899);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1538054270);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5714ffd0-f72b-4072-8a74-e5be795139b5}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1537986600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1538070464);
user_pref("browser.onboarding.notification.prompt-count", 1);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\",\"addSearchEngine\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1538072285614");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1538074099614");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1538070477965");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1538074077965");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1538070466");
user_pref("browser.slowStartup.averageTime", 10439);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20180913170256");
user_pref("browser.startup.homepage_override.mstone", "62.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.matchBuckets", "general:5,suggestion:Infinity");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1538054353688");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "62.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "62.0");
user_pref("extensions.lastPlatformVersion", "62.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"4f162544-a3a3-4fbc-bf4d-38d9d35f1b18\",\"webcompat@mozilla.org\":\"4dfed839-7b37-4b78-8cea-ab8872801eb1\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1538054925);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1538070595);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180913170256");
user_pref("media.gmp-manager.lastCheck", 1538070591);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1538054926);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f1bccda9-956f-4edb-8a97-110d64715e6e");
user_pref("services.blocklist.addons.checked", 1537961389);
user_pref("services.blocklist.clock_skew_seconds", 93400);
user_pref("services.blocklist.gfx.checked", 1537961389);
user_pref("services.blocklist.last_etag", "\"1537961387320\"");
user_pref("services.blocklist.last_update_seconds", 1537961389);
user_pref("services.blocklist.onecrl.checked", 1537961389);
user_pref("services.blocklist.pinning.checked", 1537961389);
user_pref("services.blocklist.plugins.checked", 1537961389);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1538054925);
user_pref("toolkit.startup.last_success", 1538070455);
user_pref("toolkit.telemetry.cachedClientID", "b0f6cd88-378f-4f2e-9b06-dff9451b47e1");
user_pref("toolkit.telemetry.previousBuildID", "20180913170256");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
